// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi0fgI50vGN2454D6R0N77RRn6fr55BYU',
    appId: '1:267727430854:web:e5a572728c5db3269723c7',
    messagingSenderId: '267727430854',
    projectId: 'attendo-650c4',
    authDomain: 'attendo-650c4.firebaseapp.com',
    storageBucket: 'attendo-650c4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC93m_jcokUhK80p4_0uJAzKl8w2nCnTDQ',
    appId: '1:267727430854:android:ae8d1fbdb66817569723c7',
    messagingSenderId: '267727430854',
    projectId: 'attendo-650c4',
    storageBucket: 'attendo-650c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5zuDxyYnhyORsIthPDDp8wk8zhvsiPhs',
    appId: '1:267727430854:ios:1b2d36c4add67fab9723c7',
    messagingSenderId: '267727430854',
    projectId: 'attendo-650c4',
    storageBucket: 'attendo-650c4.firebasestorage.app',
    iosBundleId: 'com.tuition.attendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5zuDxyYnhyORsIthPDDp8wk8zhvsiPhs',
    appId: '1:267727430854:ios:1b2d36c4add67fab9723c7',
    messagingSenderId: '267727430854',
    projectId: 'attendo-650c4',
    storageBucket: 'attendo-650c4.firebasestorage.app',
    iosBundleId: 'com.tuition.attendanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAi0fgI50vGN2454D6R0N77RRn6fr55BYU',
    appId: '1:267727430854:web:7e5dec1b3349ca6a9723c7',
    messagingSenderId: '267727430854',
    projectId: 'attendo-650c4',
    authDomain: 'attendo-650c4.firebaseapp.com',
    storageBucket: 'attendo-650c4.firebasestorage.app',
  );
}
